import = [
  "~/.config/alacritty/colorschemes/rose-pine.toml"
]
[env]
TERM = "xterm-256color"
[window]
padding.x = 4
padding.y = 4
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt="Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14
