#!/usr/bin/env bash

echo "========== Installing Xcode ========"
xcode-select --install
echo "========== Xcode Installed! ========"

echo "========== Installing Homebrew ========"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "========== Homebrew Installed! ========"

echo "========== Installing NVM ========"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
echo "========== NVM Installed! ========"


