#!/usr/bin/env bash

git clone git@github.com:neovim/neovim.git $HOME/neovim
cd $HOME/neovim
git fetch

brew install ninja cmake gettext curl

cd $HOME/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

echo "========= Neovim Installed! ====="
